### ISSUE TITLE
Sentencia invalida

### ISSUE THREAD

**Issue by AlcidesMereles** [Mariani88/compiladores#3]
El analizador debería lanzar un error en el siguiente codigo:
main{
  5+5;
}

**Comment by GabrielPenaU3F** [comment]
Eso dijimos q se puede en nuestro lenguaje!

**Comment by AlcidesMereles** [comment]
¿Pero que sentido tendria? Lo corregí en la otra rama porque si el resultado de la operacion no está asignado a una variable no se puede usar,nunca se podría referenciar,es una sentencia sin sentido. Igual no es algo de lo que me esté ocupando ahora,la rama master no la toqué,sigue tal cual como la subió Matias,todo lo que cambié está en la otra.

**Comment by GabrielPenaU3F** [comment]
Que sentido tendria? Ninguno. Es un lenguaje nomas. Podemos poner lo que se
nos cante, no es necesario que tenga ningun sentido. No hagas trabajo al
pedo, no queremos un lenguaje que sirva, queremos un lenguaje que nos
apruebe la materia. O al menos Mati y yo queriamos eso.

**Comment by GabrielPenaU3F** [comment]
Concentremonos en que la sintaxis ande bien y nos reconozca las reglas
correctamente. Yo para el lunes prometo agregar ya corregidas las
sentencias de if y while con las condiciones logicas
